name: Library Release

on:
  workflow_dispatch:
    inputs:
      semverType:
        description: "Release type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

env:
  NODE_VERSION: 16
  NODE_CACHE: "yarn"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.ARABOT_PAT_TRIGGER_WORKFLOW }}
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NODE_CACHE }}
      - name: Update package version
        run: yarn version --${{ github.event.inputs.semverType }} --no-git-tag-version
      - name: Get new package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Update changelog
        uses: actions/github-script@v6.4.1
        env:
          version: ${{ steps.package-version.outputs.current-version}}
        with:
          script: |
            const updateChangelog = require('./.github/scripts/update-changelog.js');
            await updateChangelog({ github, context, core });
      - name: Commit changes
        id: commit-changes
        run: |
          git config --global user.name "Arabot-1"
          git config --global user.email "arabot-1@users.noreply.github.com"
          git add --all
          git commit -am "Publish v${{ steps.package-version.outputs.current-version}}"
          git push
          echo "commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Create tag
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.ARABOT_PAT_TRIGGER_WORKFLOW }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${{ steps.package-version.outputs.current-version }}`,
              sha: "${{ steps.commit-changes.outputs.commit-sha }}"
            })
